# Security Mesh Configuration

# Policy file location
policy_file: security_policy.yaml

# Threat intelligence sources
threat_intelligence_sources:
  - type: api
    url: https://api.threatintel.example.com/v1/feed
    auth_type: oauth2
  - type: file
    path: /var/security/threat_feeds/daily.json
    format: json

# Credential stores
credential_stores:
  - type: vault
    url: https://vault.example.com
    auth_type: token
  - type: aws
    region: us-west-2
    auth_type: iam

# Protocol registry
protocol_registry:
  tls_1_3:
    name: TLS 1.3
    min_strength: 256
    supported_ciphers:
      - TLS_AES_256_GCM_SHA384
      - TLS_CHACHA20_POLY1305_SHA256
  aes_256:
    name: AES-256
    mode: GCM
    key_length: 256
  rsa_4096:
    name: RSA-4096
    key_length: 4096
    padding: OAEP 